EPUAT/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDathang = new HashSet<CTDathang>();
        }
    
        public int Id { get; set; }
        public string images { get; set; }
        public string Name { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> giamgia { get; set; }
        public Nullable<int> IdSP { get; set; }
        public Nullable<int> TB { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDathang> CTDathang { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
    }
}

EPUAT/Areas/Admin/Controllers/SanPhamController.cs
using EPUAT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;



namespace EPUAT.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: Admin/SanPham
        public ActionResult Index()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            //var check1 = (from item in db.SanPham orderby item.Gia ascending select item).ToList();
            return View(lst);
        }
        public ActionResult Add()

        {
            return View();
        }

        //POST: Add category from model
        [HttpPost]
        public ActionResult Add(SanPham obj)
        {
            //Thuc hien insert obj vao db
            try
            {
                //B1: tao dbContext
                demoEntities4 db = new demoEntities4();
                var f = Request.Files["fileImg"];
                if (f != null && f.ContentLength > 0)
                {
                    string[] ext = f.FileName.Split('.');
                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "." + ext[ext.Length - 1];
                    string path = Server.MapPath("~/images/" + fileName);
                    f.SaveAs(path);
                    obj.images = "/images/" + fileName;
                }
                //B2: thực hiện truy vấn thêm dữ liệu
                db.SanPham.Add(obj);
                db.SaveChanges();
                ViewBag.Message = "Thêm mới thành công";
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "Thêm mới thất bại";
            }
            return View();
        }
        public ActionResult Delete(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            demoEntities4 db = new demoEntities4();
            SanPham obj = db.SanPham.Find(ID);
            return View(obj);
        }
        public ActionResult DeleteByID(int ID)
        {
            demoEntities4 db = new demoEntities4();
            SanPham obj = db.SanPham.Find(ID);
            db.SanPham.Remove(obj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            demoEntities4 db = new demoEntities4();
            SanPham SP = db.SanPham.Find(ID);
            return View(SP);
        }
        public ActionResult EditbyID(SanPham SP)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            demoEntities4 db = new demoEntities4();
            var f = Request.Files["fileImg"];
            if (f != null && f.ContentLength > 0)
            {
                string[] ext = f.FileName.Split('.');
                string fileName = DateTime.Now.ToString("yyyyMMddHHmmssffff") + '.' + ext[ext.Length - 1];
                string path = Server.MapPath("~/images/" + fileName);
                f.SaveAs(path);
                SP.images = "/images/" + fileName;
                db.Entry(SP).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Product
        public ActionResult Search(int? IdSP, string Search)
        {
            demoEntities4 db = new demoEntities4();
            List<SanPham> LSP;
            if (IdSP == null && Search == null)
            {
                LSP = db.SanPham.ToList();
            }
            else
            {
                if (IdSP != null)
                {
                    LSP = db.SanPham.Where(x => x.Id == IdSP).ToList();
                }
                else
                {
                    LSP = db.SanPham.Where(x => x.Name.Contains(Search)).ToList();
                }
            }

            ViewBag.category = new SelectList(db.DanhMucSanPham.ToList(), "id", "NameSP");

            return View(LSP);
        }
        public ActionResult show(int ID)
        {
            // lấy dữ liệu của Category theo Id tương ứng
            demoEntities4 db = new demoEntities4();
            SanPham SP = db.SanPham.Find(ID);
            return View(SP);
        }
        public ActionResult showbyID(SanPham SP)
        {
            demoEntities4 db = new demoEntities4();
            SanPham obj = db.SanPham.Find(SP);
            List<SanPham> lst = db.SanPham.ToList();
            return View(lst);
        }
    }
}

EPUAT/Controllers/TrangChuController.cs
using EPUAT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace EPUAT.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        public ActionResult Index()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            var check1 = (from item in db.SanPham orderby item.Gia ascending select item).ToList();
            var check2 = (from item in db.SanPham orderby item.Gia descending select item).ToList();
            return View(lst);
        }
        public ActionResult SanPham()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            return View(lst);
        }
        public ActionResult Detail(int id)
        {
            demoEntities4 db = new demoEntities4();
            var objproduct = db.SanPham.Where(n => n.Id == id).FirstOrDefault();
            return View(objproduct);
        }
        public ActionResult SanPham1()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            //var check1 = (from item in db.SanPham  where item.IdSP == 1 select item.Name).ToList();
            return View(lst);
        }
        public ActionResult SanPham2()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            //var check1 = (from item in db.SanPham  where item.IdSP == 1 select item.Name).ToList();
            return View(lst);
        }
        public ActionResult SanPham3()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các sản phẩm truy vấn dữ liệu từ Category
            List<SanPham> lst = db.SanPham.ToList();
            //var check1 = (from item in db.SanPham  where item.IdSP == 1 select item.Name).ToList();
            return View(lst);
        }
    }
}

EPUAT/Views/TrangChu/Detail.cshtml
@model  EPUAT.Models.SanPham
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}

    <div class="body_main">
        <div class="Box_main">
            <div class="Box_main_left">
                <div class="left_top">
                    <img class="SP_img" src="@Model.images" alt="">

                </div>
            </div>
            <div class="Box_main_right">
                <div class="right_title">
                    <a class="top-contentleft_text" href="Trangchu.html">TRANG CHỦ</a>
                    <p> &nbsp; / &nbsp;&nbsp; </p>
                    <a class="top-contentleft_text" href="Sanpham.html" style="color: black;"><b>CỬA HÀNG</b></a>
                </div>
                <div>
                    <h1 style="color:crimson">
                        @Model.Name
                    </h1>
                </div>
                <div>
                    <h2>
                        @string.Format("{0:#,0}", Model.Gia)₫
                    </h2>
                </div>
                <div>
                    <h2 style="margin-bottom:0px ;">
                        Mô tả:
                    </h2>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 310px;height: 50px;">
                    <h4>CPU :</h4>
                    <p> MT3562 Octa Core, ARM Cortext-A53</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 120px;height: 50px;">
                    <h4>Tần số :</h4>
                    <p>1.6GHz</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 200px;height: 50px;">
                    <h4>Bộ nhớ RAM :</h4>
                    <p> DDR3 2GB</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 310px;height: 50px;">
                    <h4>Bộ nhớ ROM :</h4>
                    <p>Tích hợp bộ nhớ trong 16GB</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 200px;height: 50px;">
                    <h4>Màn Hình:</h4>
                    <p> IPS 10Inch</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items: center; width: 200px;height: 50px;">
                    <h4>Độ phân giải:</h4>
                    <p> IPS 10Inch</p>
                </div>
                <div style="display: flex;justify-content: space-between;align-items:center; width: 300px;height: 50px;">
                    @*<div>
                        <input type="number" id="tentacles" name="tentacles" min="1" max="100" value="1">
                    </div>*@
                    <div>
                        <a href="/Cart/AddToCart/@Model.Id" class="detail">Thêm vào giỏ</a>
                    </div>
                </div>
            </div>
        </div>

    </div>

EPUAT/Views/TrangChu/SanPham.cshtml
@model List<EPUAT.Models.SanPham>
@{
    ViewBag.Title = "SanPham";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}
<div class="body">
    <div class="body_main">
        <div class="body_top">
            <div class="top-contentleft">
                <a class="top-contentleft_text" href="/Trangchu/index">TRANG CHỦ</a>
                <p> &nbsp; / &nbsp;&nbsp; </p>
                <a class="top-contentleft_text" href="/Trangchu/SanPham" style="color: black;"><b>CỬA HÀNG</b></a>
            </div>
            <div class="top-contentright">
                <p class="top-contentleft_text"> Hiển thị một kết quả duy nhất </p>
                <select style="width: 255px;height: 38px;" id="option" name="option">
                    <option class="top-contentleft_text" value="Thứ tự theo giá">
                        Thứ tự theo giá
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: thấp đến cao">
                        Thứ tự theo giá: thấp
                        đến
                        cao
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: cao xuống thấp">
                        Thứ tự theo giá:
                        cao
                        xuống thấp
                    </option>
                </select>
            </div>
        </div>
    </div>
    <div class="body_main_bt">
        <div class="left_item">
            <div class="listSP">
                <div class="listSP_title">
                    <h3>DANH MỤC SẢN PHẨM</h3>
                </div>
                <div>
                        <a class="listSP_item" href="~/TrangChu/SanPham">Màn Hình Xe Hơi</a>
                    </div>
                    <div>
                        <a class="listSP_item" href="~/TrangChu/SanPham1">Camera hành trình</a>
                    </div>
                    <div>
                        <a class="listSP_item" href="~/TrangChu/SanPham2">Camera 360</a>
                    </div>
                    <div>
                        <a class="listSP_item" href="~/TrangChu/SanPham3">Camera lùi</a>
                    </div>
            </div>
            <div class="listSP " style="height: 450px;">
                <div class="listSP_title">
                    <h3>SẢN PHẨM</h3>
                </div>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/DDPAI-360.jpg" class="list_img">
                        </div>
                        <div style=" text-decoration: none;">
                            <p style="margin:5px 0px ;">Camera hành trình 360</p>
                            <p style="margin:5px 0px ;">1,516,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-omniview.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Omnivue</p>
                            <p style="margin:5px 0px ;">18,900,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-panorama-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Panorama</p>
                            <p style="margin:5px 0px ;">16,900,000 ₫</p>
                        </div>
                    </div>
                </a>

                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Omnivue-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera quan sát 360 độ</p>
                            <p style="margin:5px 0px ;">18,899,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Esky-EC170-20.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Hệ thống camera lùi ..</p>
                            <p style="margin:5px 0px ;">667,000 ₫</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="right_item">
            <div class="item_SP">
                @foreach (var item in Model)
                {
                    if (item.TB == 1)
                    {
                    <div class="frames_box_SP">
                        <div style="overflow: hidden;">
                            <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                <img src="@item.images" alt="logo" class="frames_box_img_SP">
                            </a>
                        </div>
                        <div class="frames_text">
                            <p>@item.Name</p>
                        </div>
                        <div class="frames_text_price">
                            <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                        </div>
                        <div style="margin-top: 30px; text-align: center;">
                            <a href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            @*@Html.ActionLink("THÊM VÀO GIỎ", "AddToCart", "Cart", new { ProductId = item.Id }, new { @class = "frames_button_buy" })*@
                        </div>
                    </div>
                    }
                }
            </div>
        </div>
    </div>

</div>

EPUAT/Views/TrangChu/SanPham1.cshtml
@{
    ViewBag.Title = "SanPham1";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}

<div class="body">
    <div class="body_main">
        <div class="body_top">
            <div class="top-contentleft">
                <a class="top-contentleft_text" href="/Trangchu/index">TRANG CHỦ</a>
                <p> &nbsp; / &nbsp;&nbsp; </p>
                <a class="top-contentleft_text" href="/Trangchu/SanPham1" style="color: black;"><b>CỬA HÀNG</b></a>
            </div>
            <div class="top-contentright">
                <p class="top-contentleft_text"> Hiển thị một kết quả duy nhất </p>
                <select style="width: 255px;height: 38px;" id="option" name="option">
                    <option class="top-contentleft_text" value="Thứ tự theo giá">
                        Thứ tự theo giá
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: thấp đến cao">
                        Thứ tự theo giá: thấp
                        đến
                        cao
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: cao xuống thấp">
                        Thứ tự theo giá:
                        cao
                        xuống thấp
                    </option>
                </select>
            </div>
        </div>
    </div>
    <div class="body_main_bt">
        <div class="left_item">
            <div class="listSP">
                <div class="listSP_title">
                    <h3>DANH MỤC SẢN PHẨM</h3>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham">Màn Hình Xe Hơi</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham1">Camera hành trình</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham2">Camera 360</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham3">Camera lùi</a>
                </div>
            </div>
            <div class="listSP " style="height: 450px;">
                <div class="listSP_title">
                    <h3>SẢN PHẨM</h3>
                </div>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/DDPAI-360.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera hành trình 360</p>
                            <p style="margin:5px 0px ;">1,516,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-omniview.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Omnivue</p>
                            <p style="margin:5px 0px ;">18,900,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-panorama-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Panorama</p>
                            <p style="margin:5px 0px ;">16,900,000 ₫</p>
                        </div>
                    </div>
                </a>

                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Omnivue-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera quan sát 360 độ</p>
                            <p style="margin:5px 0px ;">18,899,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Esky-EC170-20.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Hệ thống camera lùi ..</p>
                            <p style="margin:5px 0px ;">667,000 ₫</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="right_item">
            <div class="item_SP">
                @foreach (var item in Model)
                {
                    if (item.TB == 2)
                    {
                        <div class="frames_box_SP">
                            <div style="overflow: hidden;">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="@item.images" alt="logo" class="frames_box_img_SP">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name</p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                @*@Html.ActionLink("THÊM VÀO GIỎ", "AddToCart", "Cart", new { ProductId = item.Id }, new { @class = "frames_button_buy" })*@
                                <a href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>

</div>

EPUAT/Views/TrangChu/SanPham2.cshtml
@{
    ViewBag.Title = "SanPham2";
    Layout = "~/Views/Shared/TrangChu.cshtml";
}

<div class="body">
    <div class="body_main">
        <div class="body_top">
            <div class="top-contentleft">
                <a class="top-contentleft_text" href="/Trangchu/index">TRANG CHỦ</a>
                <p> &nbsp; / &nbsp;&nbsp; </p>
                <a class="top-contentleft_text" href="/Trangchu/SanPham2" style="color: black;"><b>CỬA HÀNG</b></a>
            </div>
            <div class="top-contentright">
                <p class="top-contentleft_text"> Hiển thị một kết quả duy nhất </p>
                <select style="width: 255px;height: 38px;" id="option" name="option">
                    <option class="top-contentleft_text" value="Thứ tự theo giá">
                        Thứ tự theo giá
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: thấp đến cao">
                        Thứ tự theo giá: thấp
                        đến
                        cao
                    </option>
                    <option class="top-contentleft_text" value="Thứ tự theo giá: cao xuống thấp">
                        Thứ tự theo giá:
                        cao
                        xuống thấp
                    </option>
                </select>
            </div>
        </div>
    </div>
    <div class="body_main_bt">
        <div class="left_item">
            <div class="listSP">
                <div class="listSP_title">
                    <h3>DANH MỤC SẢN PHẨM</h3>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham">Màn Hình Xe Hơi</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham1">Camera hành trình</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham2">Camera 360</a>
                </div>
                <div>
                    <a class="listSP_item" href="~/TrangChu/SanPham3">Camera lùi</a>
                </div>
            </div>
            <div class="listSP " style="height: 450px;">
                <div class="listSP_title">
                    <h3>SẢN PHẨM</h3>
                </div>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/DDPAI-360.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera hành trình 360</p>
                            <p style="margin:5px 0px ;">1,516,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-omniview.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Omnivue</p>
                            <p style="margin:5px 0px ;">18,900,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Camera-360-panorama-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera 360 Panorama</p>
                            <p style="margin:5px 0px ;">16,900,000 ₫</p>
                        </div>
                    </div>
                </a>

                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Omnivue-01.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Camera quan sát 360 độ</p>
                            <p style="margin:5px 0px ;">18,899,000 ₫</p>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="listSP_item_sp">
                        <div>
                            <img src="/images/Esky-EC170-20.jpg" class="list_img">
                        </div>
                        <div>
                            <p style="margin:5px 0px ;">Hệ thống camera lùi ..</p>
                            <p style="margin:5px 0px ;">667,000 ₫</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="right_item">
            <div class="item_SP">
                @foreach (var item in Model)
                {
                    if (item.TB == 3)
                    {
                        <div class="frames_box_SP">
                            <div style="overflow: hidden;">
                                <a href="@Url.Action("Detail", "TrangChu", new {id = item.Id})">
                                    <img src="@item.images" alt="logo" class="frames_box_img_SP">
                                </a>
                            </div>
                            <div class="frames_text">
                                <p>@item.Name</p>
                            </div>
                            <div class="frames_text_price">
                                <p>@string.Format("{0:#,0}", item.Gia)₫</p>
                            </div>
                            <div style="margin-top: 30px; text-align: center;">
                                @*@Html.ActionLink("THÊM VÀO GIỎ", "AddToCart", "Cart", new { ProductId = item.Id }, new { @class = "frames_button_buy" })*@
                                <a href="/Cart/AddToCart/@item.Id" class="frames_button_buy">THÊM VÀO GIỎ</a>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>

</div>