EPUAT/Models/Dathang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dathang()
        {
            this.CTDathang = new HashSet<CTDathang>();
        }
    
        public int MaPhieuDat { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
        public string TrangThai { get; set; }
        public string DiaChi { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDathang> CTDathang { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}

EPUAT/Areas/Admin/Controllers/DatHangController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EPUAT.Models;

namespace EPUAT.Areas.Admin.Controllers
{
    public class DatHangController : Controller
    {
        // GET: Admin/DatHang
        public ActionResult Index()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các khách hàng truy vấn dữ liệu từ Khachhang
            List<Dathang> lst = db.Dathang.ToList();
            return View(lst);
        }
        public ActionResult Search(int? MKH, string Search)
        {
            demoEntities4 db = new demoEntities4();

            List<Dathang> LKH;
            if (MKH == null && Search == null)
            {
                LKH = db.Dathang.ToList();
            }
            else
            {
                if (MKH != null)
                {
                    LKH = db.Dathang.Where(x => x.MaPhieuDat == MKH).ToList();
                }
                else
                {
                    LKH = db.Dathang.Where(x => x.TenKH.Contains(Search)).ToList();
                }
            }

            //ViewBag.category = new SelectList(db.DanhMucSanPham.ToList(), "MaKH", "TenKH");

            return View(LKH);
        }
    }
}

EPUAT/Areas/Admin/Views/DatHang/Index.cshtml
@model List<EPUAT.Models.Dathang>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1200px; right: 10px">
            <h2>Quản lý đơn hàng</h2>
            @using (Html.BeginForm("Search", "DatHang", FormMethod.Get))
            {
                @*<label>Lọc theo danh mục: </label>
                    <div>
                        @Html.DropDownList("category", "-- Tất cả --")
                    </div>*@
                <label>Lọc theo tên: </label>
                <div style="padding:20px 20px 20px 0px;display:flex">
                    <div>
                        @Html.TextBox("Search")
                    </div>
                    <div><input type="submit" value="Lọc" /></div>
                </div>
            }
            <table class="table">
                <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                <th>#</th>
                <th>Tên khách hàng</th>
                <th>Thời gian đặt</th>
                <th>Trạng thái</th>
                <th>Địa chỉ</th>
                <th>Chức năng </th>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaPhieuDat</td>
                        <td>@item.TenKH</td>
                        <td>@string.Format("{0:dd/MM/yyy}", item.ThoiGianDat)</td>
                        <td>@item.TrangThai</td>
                        <td>@item.DiaChi</td>
                        <td>
                          
                            @Html.ActionLink("Xen", "check", new { ID = item.MaPhieuDat })
                        </td>
                        
                    </tr>
                }
            </table>
        </div>
    </div>
</body>
</html>

EPUAT/Areas/Admin/Views/DatHang/Search.cshtml
@model List<EPUAT.Models.Dathang>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1200px; right: 10px">
            <h2>Danh Sách đơn hàng </h2>
            <div>
                @Html.ActionLink("Thêm Mới", "Add")
                @using (Html.BeginForm("Search", "DatHang", FormMethod.Get))
                {
                    @*<label>Lọc theo danh mục: </label>
            <div>
                @Html.DropDownList("category", "-- Tất cả --")
            </div>*@
                    <label>Lọc theo tên: </label>
                    <div style="padding:20px 20px 20px 0px;display:flex">
                        <div>
                            @Html.TextBox("Search")
                        </div>
                        <div><input type="submit" value="Lọc" /></div>
                    </div>
                }

                <table class="table">
                    <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                    <th>#</th>
                    <th>Tên khách hàng</th>
                    <th>Thời gian đặt</th>mm
                    <th>Trạng thái</th>
                    <th>Địa chỉ</th>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaPhieuDat</td>
                            <td>@item.TenKH</td>
                            <td>@string.Format("{0:dd/MM/yyy}", item.ThoiGianDat)</td>
                            <td>@item.TrangThai</td>
                            <td>@item.DiaChi</td>
                            @*<td>
                        @Html.ActionLink("Sửa", "Edit", new { MaPhieuDat = item.MaPhieuDat })
                        @Html.ActionLink("Xóa", "Delete", new { MaPhieuDat = item.MaPhieuDat })
                    </td>*@
                        </tr>
                    }
                </table>
            </div>
        </div>
</body>
</html>