EPUAT/Areas/Admin/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EPUAT.Models;

namespace EPUAT.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
        // GET: Admin/ThongKe
        public ActionResult Index()
        {
            // tạo dbContext
            demoEntities4 db = new demoEntities4();
            // lấy ra danh sách các khách hàng truy vấn dữ liệu từ Khachhang
            List<CTDathang> lst = db.CTDathang.ToList();
            return View(lst);
        }
        public ActionResult Search(int? MKH, int Search)
        {
            demoEntities4 db = new demoEntities4();

            List<CTDathang> LKH;
            if (MKH == null && Search == null)
            {
                LKH = db.CTDathang.ToList();
            }
            else
            {
                if (MKH != null)
                {
                    LKH = db.CTDathang.Where(x => x.MaCTPhieuDat == MKH).ToList();
                }
                else
                {
                    LKH = db.CTDathang.Where(x => x.MaPhieuDat == Search).ToList();
                }
            }

            //ViewBag.category = new SelectList(db.DanhMucSanPham.ToList(), "MaKH", "TenKH");

            return View(LKH);
        }
    }
}

EPUAT/Areas/Admin/Views/ThongKe/Index.cshtml
@model List<EPUAT.Models.CTDathang>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1200px; right: 10px">
            <h2>Quản lý đơn hàng</h2>
            @using (Html.BeginForm("Search", "ThongKe", FormMethod.Get))
            {
                @*<label>Lọc theo danh mục: </label>
                    <div>
                        @Html.DropDownList("category", "-- Tất cả --")
                    </div>*@
                <label>Lọc theo tên: </label>
                <div style="padding:20px 20px 20px 0px;display:flex">
                    <div>
                        @Html.TextBox("Search")
                    </div>
                    <div><input type="submit" value="Lọc" /></div>
                </div>
            }
            <table class="table">
                <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                    <th>Mã CT Phiếu Đặt</th>
                    <th>Mã Phiếu Đặt </th>
                    <th>Mã sản phẩm </th>
                    <th>Số lượng </th>mm
                    <th>Thành tiền </th>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaCTPhieuDat</td>
                        <td>@item.MaPhieuDat</td>
                        <td>@item.Id</td>
                        <td>@item.Soluong</td>
                        <td>@item.ThanhTien</td>
                        @*<td>
                            @Html.ActionLink("Sửa", "Edit", new { MaCTPhieuDat = item.MaCTPhieuDat })
                            @Html.ActionLink("Xóa", "Delete", new { MaCTPhieuDat = item.MaCTPhieuDat })
                        </td>*@
                    </tr>
                }
            </table>
        </div>
    </div>
</body>
</html>

EPUAT/Areas/Admin/Views/ThongKe/Search.cshtml
@model List<EPUAT.Models.CTDathang>

@{
    Layout = null;
    Layout = "~/Areas/Admin/Views/Shared/ViewPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <div style="position: absolute; width: 1200px; right: 10px">
            <h2>Danh Sách đơn hàng </h2>
            <div>
                @using (Html.BeginForm("Search", "ThongKe ", FormMethod.Get))
                {
                    @*<label>Lọc theo danh mục: </label>
            <div>
                @Html.DropDownList("category", "-- Tất cả --")
            </div>*@
                    <label>Lọc theo Mã : </label>
                    <div style="padding:20px 20px 20px 0px;display:flex">
                        <div>
                            @Html.TextBox("Search")
                        </div>
                        <div><input type="submit" value="Lọc" /></div>
                    </div>
                }

                <table class="table">
                    <thead class="thead-dark" style="background-color: #000000d9;color: aliceblue;">
                    <th>Mã CT Phiếu Đặt</th>
                    <th>Mã Phiếu Đặt </th>
                    <th>Mã sản phẩm </th>
                    <th>Số lượng </th>mm
                    <th>Thành tiền </th>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaCTPhieuDat</td>
                            <td>@item.MaPhieuDat</td>
                            <td>@item.Id</td>
                            <td>@item.Soluong</td>
                            <td>@item.ThanhTien</td>
                            @*<td>
                        @Html.ActionLink("Sửa", "Edit", new { MaCTPhieuDat = item.MaCTPhieuDat })
                        @Html.ActionLink("Xóa", "Delete", new { MaCTPhieuDat = item.MaCTPhieuDat })
                    </td>*@
                        </tr>
                    }
                </table>

            </div>
        </div>
</body>
</html>